name: vegans develop workflow

on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_tests:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9]
        os: [macos-latest, ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "1. Clone repository"
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: "2. Set up Python ${{ matrix.python }}"
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install Tox
        run: pip install tox

      # Run tox.ini which runs pytest
      - name: Run Tox
        run: tox -e py

  check-examples:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example-name: [snippets/example_quickstart.py]
    steps:
      - name: "1. Clone repository"
        uses: actions/checkout@v2

      - name: "2. Set up Python 3.8"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: "3. Run examples ${{ matrix.example-name }}"
        run: |
          PYTHONPATH=./ python ./tutorials/${{ matrix.example-name }}



