name: Create sphinx documentation

on:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: "1. Clone repository"
        uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: "2. Set up Python 3.8"
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Sphinx & requirements
        run: pip install -r requirements/all.txt

      # Run sphinx
      - name: Run Sphinx
        run: make --directory ./docs/ clean html